project:
  type: website
  title: "HOAD Dashboard"
  output-dir: docs
  resources:
    - fonts/*
  execute-dir: project

website:
  title: "HOAD"
  site-url: https://subugoe.github.io/hoaddash/
  twitter-card: true
  open-graph: true
  page-footer:
    left: 
      - text: "This website is licensed under <a href='https://creativecommons.org/publicdomain/zero/1.0/'>CC0</a>."
    center:
      - text: "Privacy"
        href: privacy.qmd
      - text: "Imprint"
        href: https://www.sub.uni-goettingen.de/impressum/
    right:
      - icon: github
        href: https://github.com/subugoe/hoaddash/
        aria-label: Project GitHub
  sidebar:
    background: "#ffffff"
    border: false
    logo: "hoad_logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/subugoe/hoaddash
        text: "GitHub Dashboard Repo"
      - icon: "file-bar-graph"
        href: https://github.com/subugoe/hoaddata
        text: "GitHub Data Repo"
      - icon: "bug"
        text: "Report a Bug"
        href: https://github.com/subugoe/hoaddash/issues
    style: "docked"
    search: true
    collapse-level: 1
    contents:
          - section: "Publishers"
            contents:
              - text: Overview
                href: index.qmd
              - href: jct/elsevier/index.qmd
                text: "Elsevier"
              - href: jct/springernature/index.qmd
                text: Springer Nature
              - href: jct/wiley/index.qmd
                text: Wiley
              - section: "Others"
                contents:
                  - text: American Chemical Society 
                    href: jct/americanchemicalsociety/index.qmd
                  - text: "American Physical Society"
                    href: jct/americanphysicalsociety/index.qmd
                  - text: "BMJ Publishing"
                    href: jct/bmjpublishing/index.qmd
                  - text: "Cambridge University Press"
                    href: jct/cambridgeuniversitypress/index.qmd
                  - text: "Karger"
                    href: jct/karger/index.qmd
                  - text: "IEEE"
                    href: jct/ieee/index.qmd
                  - text: "IOP Publishing"
                    href: jct/ioppublishing/index.qmd
                  - text: "Oxford University Press"
                    href: jct/oxforduniversitypress/index.qmd
                  - text: "Royal Society of Chemistry"
                    href: jct/royalsocietyofchemistry/index.qmd
                  - text: "Sage"
                    href: jct/sage/index.qmd
                  - href: jct/taylorandfrancis/index.qmd
                    text: Taylor and Francis
                  - text: "Thieme"
                    href: jct/thieme/index.qmd
                  - text: "Walter de Gruyter"
                    href: jct/walterdegruyter/index.qmd
          - section: "Agreements with German consortia"
            contents:
              - text: "Overview"
                href: oam/index.qmd
              - section: "Consortia"
                contents:
                  - section: "DEAL"
                    contents:
                      - text: "Elsevier"
                        href: "oam/elsevierdeal/index.qmd"
                      - text: "Springer"
                        href: oam/springerhybriddeal/index.qmd
                      - text: "Wiley"
                        href: oam/wileyhybriddeal/index.qmd
                  - section: "BSB"
                    contents: 
                      - text: "BMJ"
                        href: oam/bmjbsb/index.qmd
                      - text: "CUP"
                        href: oam/cupbsb/index.qmd
                      - text: "Karger"
                        href: oam/kargerbsb/index.qmd
                      - text: "Sage"
                        href: oam/sagebsb/index.qmd
                  - section: "MPDL"
                    contents:
                      - text: "Nature"
                        href: oam/naturempdl/index.qmd
                  - section: "SUB Göttingen"
                    contents:
                       - text: "De Gruyter"
                         href: oam/degruytersubgöttingen/index.qmd
                       - text: "Hogrefe"
                         href: oam/hogrefesubgöttingen/index.qmd
                  - section: "TIB"
                    contents:
                        - text: "ESC"
                          href: oam/ecstib/index.qmd 
                        - text: "IOP"
                          href: oam/ioptib/index.qmd 
                        - text: "Portland Press"
                          href: oam/portlandpresstib/index.qmd
                        - text: "RSC"
                          href: oam/rsctib/index.qmd
                  - section: "ZBMED"
                    contents:
                       - text: "Thieme"
                         href: oam/thiemezbmed/index.qmd
                  - section: "ZBW"
                    contents:
                       - text: "Taylor and Francis"
                         href: oam/taylorfranciszbw/index.qmd
          - text: "About"
            href: "about.qmd"
    footer: funding_note.md
format:
  html:
    theme: [cosmo, styles.scss]
    grid:
      sidebar-width: 300px
      
execute:
  cache: false