---
format: html
execute:
  echo: false
  warnings: false
  message: false
---

```{r}
library(dplyr)
library(glue)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r, message = FALSE}
#' ## Global Creative Commons prevalence
#'
#' Calculate CC license variants by year. Returns absulote and relative values.
cc_ind_global <- function() {
  cc_df <- cc_jn_ind %>%
    group_by(cr_year, cc) %>%
    summarise(cc_total = sum(cc_total))
  all_df <- cc_jn_ind %>%
    distinct(cr_year, jn_id, jn_all) %>%
    group_by(cr_year) %>%
    summarise(jn_all = sum(jn_all))
  inner_join(cc_df, all_df) %>%
    filter(!is.na(cc)) %>%
    mutate(prop = cc_total / jn_all) %>%
   # select(-jn_all) %>%
    ungroup() %>%
    # missing combinations
    tidyr::complete(cr_year, cc, fill = list(cc_total = 0, prop = 0)) %>%
    distinct() %>%
    ungroup()
}
#' Publications 2017 - 2022
all_publications <- cc_ind_global() |>
  distinct(cr_year, jn_all) |>
  pull(jn_all) |>
  sum(na.rm = TRUE)
#' Publications 2021
all_publications_2021 <-
  cc_ind_global() |>
  distinct(cr_year, jn_all) |>
  filter(cr_year == "2021") |>
  pull(jn_all) |>
  sum(na.rm = TRUE)
#' CC publications 2017 - 2022
cc_publications <- cc_ind_global() |>
  pull(cc_total) |>
  sum(na.rm = TRUE)
#' CC publications 2021
cc_publications_21 <- cc_ind_global() |>
  filter(cr_year == "2021") |>
  pull(cc_total) |>
  sum(na.rm = TRUE)

#' ## Germany Creative Commons prevalence
#'
#' Calculate CC license variants by year. Returns absulote and relative values.
cc_ind_de <- function() {
  de_df <- cc_openalex_inst_jn_ind |>
    filter(country_code == "DE")

  de_total <- de_df |>
    distinct(cr_year, jn_id, articles_total) %>%
    group_by(cr_year) %>%
    summarize(jn_all = sum(articles_total))
  de_cc <- de_df |>
    filter(!is.na(cc)) |>
    distinct(cr_year, jn_id, articles_under_cc_variant, cc) |>
    group_by(cr_year, cc) |>
    summarize(cc_total = sum(articles_under_cc_variant))
  left_join(de_total, de_cc, by = c("cr_year")) |>
    mutate(cr_year = factor(cr_year)) %>%
    mutate(prop = cc_total / jn_all) %>%
    mutate_if(is.numeric, ~replace(., is.na(.), 0))
}

#' Publications 2017 - 2022
all_publications_de <- cc_ind_de() |>
  distinct(cr_year, jn_all) |>
  pull(jn_all) |>
  sum(na.rm = TRUE)
#' Publications 2021
all_publications_2021_de <-
  cc_ind_de() |>
  distinct(cr_year, jn_all) |>
  filter(cr_year == "2021") |>
  pull(jn_all) |>
  sum(na.rm = TRUE)
#' CC publications 2017 - 2022
cc_publications_de <- cc_ind_de() |>
  pull(cc_total) |>
  sum(na.rm = TRUE)
#' CC publications 2021
cc_publications_21_de <- cc_ind_de() |>
  filter(cr_year == "2021") |>
  pull(cc_total) |>
  sum(na.rm = TRUE)


## Indicator display
basic_stat <- function(...) {
glue::glue('<div class="grid">
 <div class="g-col-lg-6 g-col-12">
 <p style="text-align: center;" class="text-muted">2017-2022</p>
  <table style="margin:auto;padding:0;width:80%;text-align: center;">
  <colgroup>
       <col span="1" style="width: 50%;">
       <col span="1" style="width: 50%;">
      </colgroup>
    <tbody>
      <tbody>
         <tr >
            <td colspan="1"  scope="row" style="border-top: 1px solid rgb(255, 255, 255); font-size: 100%;">Global</td>
            <td colspan="1"  style="border-top: 1px solid rgb(255, 255, 255); font-size: 100%; border-left: 1px solid rgb(26, 55, 113);">Germany</td>
         </tr>
          <tr >
            <td colspan="1"  scope="row" style="font-size: 157%;">{round(cc_publications / all_publications * 100, 1)}%</td>
            <td colspan="1"  style="font-size: 157%; border-left: 1px solid rgb(26, 55, 113);">{round(cc_publications_de / all_publications_de * 100, 1)}%</td>
         </tr>
         <tr >
            <td colspan="1"  scope="row" style="border-top: 1px solid rgb(255, 255, 255); color: rgb(102, 102, 102); font-size: 91%;">{paste0(format(round(cc_publications / 1e3, 0), trim = TRUE), "K")} out of {paste0(format(round(all_publications / 1e6, 1), trim = TRUE), "Mio")}</td>
            <td colspan="1"  style="border-top: 1px solid rgb(255, 255, 255); color: rgb(102, 102, 102); font-size: 91%; border-left: 1px solid rgb(26, 55, 113);">{paste0(format(round(cc_publications_de / 1e3, 0), trim = TRUE), "K")} out of {paste0(format(round(all_publications_de / 1e3, 0), trim = TRUE), "K")}</td>
         </tr>
      </tbody>
   </table>
</div>
 <div class="g-col-lg-6 g-col-12">
 <p style="text-align: center;" class="text-muted">2021</p>
 <table style="margin:auto;padding:0;width:80%;text-align: center;">
  <colgroup>
       <col span="1" style="width: 50%;">
       <col span="1" style="width: 50%;">
      </colgroup>
    <tbody>
      <tbody>
         <tr >
            <td colspan="1"  scope="row" style="border-top: 1px solid rgb(255, 255, 255); font-size: 100%;">Global</td>
            <td colspan="1"  style="border-top: 1px solid rgb(255, 255, 255); font-size: 100%; border-left: 1px solid rgb(26, 55, 113);">Germany</td>
         </tr>
         <tr >
            <td colspan="1"  scope="row" style="font-size: 157%;">{round(cc_publications_21 / all_publications_2021 * 100, 1)}%</td>
            <td colspan="1"  style="font-size: 157%; border-left: 1px solid rgb(26, 55, 113);">{round(cc_publications_21_de / all_publications_2021_de * 100, 1)}%</td>
         </tr>
         <tr >
            <td colspan="1"  scope="row" style="border-top: 1px solid rgb(255, 255, 255); color: rgb(102, 102, 102); font-size: 91%;">{paste0(format(round(cc_publications_21 / 1e3, 0), trim = TRUE), "K")} out of {paste0(format(round(all_publications_2021 / 1e3, 0), trim = TRUE), "K")}</td>
            <td colspan="1"  style="border-top: 1px solid rgb(255, 255, 255); color: rgb(102, 102, 102); font-size: 91%; border-left: 1px solid rgb(26, 55, 113);">{paste0(format(round(cc_publications_21_de / 1e3, 0), trim = TRUE), "K")} out of {paste0(format(round(all_publications_2021_de / 1e3, 0), trim = TRUE), "K")}</td>
         </tr>
      </tbody>
   </table>
</div>
</div>')
  }
```

```{r, message = FALSE, results = 'asis', echo = FALSE}
basic_stat()
```