---
format:
  html:
    theme: default
    toc: false
---

:::{.callout-warning}

Under construction. This website officially launches end of 2022.

:::

# How open are hybrid journals in transformative agreements? 

As library consortia increasingly negotiate transformative
agreements, HOAD highlights the degree to which hybrid journals included in commercial publisher portfolios have transitioned to full open access since 2017.

Our resources can help libraries and consortia model 
for a fully open access future and derive key insights such as:

- How much content in hybrid journals is already published open access under a Creative Commons license?
- How does the distribution of Germany's output in hybrid journals relate to that of other countries?
- Are metadata made openly available and if not, where are the gaps?

The dashboard provides complementary analytical views on two openly available data collections of hybrid journals included in transformative agreements:

- **JCT**: [Transformative Agreements Public Data](https://journalcheckertool.org/transformative-agreements/) exposed by the [cOAlition S'](https://www.coalition-s.org/) [Journal Checker Tool](https://journalcheckertool.org/)
- **OAM**: [Consortial Agreements in Germany](https://doi.org/10.26165/JUELICH-DATA/VTQXLM) as included by the FZ JÜlich in its [Open Access Monitor](https://open-access-monitor.de/)

To engage with everyone, our open source data analysis combines open data from [Crossref](https://www.crossref.org/), [OpenAlex](https://openalex.org/) and [Unpaywall](https://unpaywall.org/).

