---
title: "Data re-use and licenses"
format:
  html:
    theme: default
    toc: false
---

This work released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute these materials in any form, for any purpose, commercial or non-commercial, and by any means.

Please note that the information provided here reflects our current understanding and is likely to change. We work hard to keep it up to date and accurate, but we do not accept any liability in relation to any errors or omissions.

Crossref asserts no claims of ownership to individual items of bibliographic metadata and associated Digital Object Identifiers (DOIs) acquired through the use of the Crossref Free Services. Individual items of bibliographic metadata and associated DOIs may be cached and incorporated into the user's content and systems.

OpenAlex data and transformative agreement data from the cOAlition S are made available under the CC0 license.

This work re-used the following dataset:

Pollack, Philipp; Lindstrot, Barbara; Barbers, Irene, Stanzel, Franziska, 2021, "Open Access Monitor: Zeitschriftenlisten (V2)", <https://doi.org/10.26165/JUELICH-DATA/VTQXLM>.

published under CC BY 4.0.